default_env: dev

environments:
  mock:
    base_url: "https://reqres.in/api"
    api_key: "mock-key"
  dev:
    base_url: "https://reqres.in/api"
    api_key: "dev-key"
  stage:
    base_url: "https://staging.reqres.in/api"
    api_key: "stage-key"
  prod:
    base_url: "https://api.reqres.in"
    api_key: "prod-key"
