default_env: dev

environments:
  mock:
    base_url: "https://reqres.in/api"
    api_key: ""
  dev:
    base_url: "https://reqres.in/api"
    api_key: ""
  stage:
    base_url: "https://staging.reqres.in/api"
    api_key: ""
  prod:
    base_url: "https://api.reqres.in"
    api_key: ""
